### ISSUE TITLE
Gdb-port option in spike.cc

### ISSUE THREAD

**Issue by ninode** [lowRISC/riscv-isa-sim#1]
Hello, 

When attempting to get the RISC-V sources, I'm using lowrisc-chip repository with build.sh and regression.sh. Debugging with spike in interactive mode works percfectly. However, debugging with gdb is not uspported in this version as oppose to the riscv/riscv-isa-sim spike version. 

Could you please tell me how can I fix this in simple terms ? I'm new to this.

Thank you

**Comment by wsong83** [comment]
Sorry, there is probably no easy way to fix it besides using the latest riscv-isa-sim from riscv.
We are still using an old version of Rocket which does not have the run-control debugger.
The planned time line to have this supported in hardware probably is in the later half of this year.

Spike is an instruction set simulator. Is there any particular reason for you to use the Spike from lowRISC? We actually have not change anything significant in Spike.
